config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  devise_for :users
  resources :home, only: :index
  resources :cvs do
    resources :jobs
  end
  resources :cvs do
    resources :schools
  end
  resources :cvs do
    resources :projects
  end
  resources :cvs do
    resources :blogs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :cv, optional: true
end

app/models/cv.rb
class Cv < ActiveRecord::Base
  has_many :schools
  has_many :jobs
  has_many :projects
  has_many :blogs

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :schools
  has_many :jobs
  has_many :projects
  has_many :blogs
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :cv, optional: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :cv, optional: true
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :cv, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authorize
    if !current_user
      flash[:alert] = "Please sign in to visit this page."
      redirect_to '/'
    end
  end

  def authorize_admin
    if current_user.admin === true
      new_cv_path
    else
      flash[:alert] = "Only an admin can visit this page."
      redirect_to '/'
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authorize_admin, only: [:edit]
  def index
    @cv = cv.find(params[:cv_id])
    @blogs = Blog.all
    @schools = School.all
    @projects = Project.all
  end

  def new
    @cv = Cv.find(params[:cv_id])
    @blog = @cv.blogs.new
  end

  def create
    @cv = Cv.find(params[:cv_id])
    @blog = @cv.blogs.new(blog_params)
    if @blog.save
      flash[:alert] = "Blog Successfully Added"
      redirect_to cv_path(@blog.cv)
    else
      flash[:alert] = "Rating should be between 1 and 5"
      render :new
    end
  end

  def edit
    @cv = Cv.find(params[:cv_id])
    @blog = Blog.find(params[:id])
  end

  def update
    @cv = Cv.find(params[:cv_id])
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      flash[:alert] = "Blog Successfully Updated"
      redirect_to cv_path(@blog.cv)
    else
      flash[:alert] = "Rating should be between 1 and 5"
      render :edit
    end
  end

  def destroy
    @cv = Cv.find(params[:cv_id])
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to cv_path(@blog.cv)
  end

private
  def blog_params
    params.require(:blog).permit(:title, :description)
  end
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_action :authorize, only: [:index, :new]
  before_action :authorize_admin, only: [:edit]
def index
    @cvs = Cv.all
  end

def show
  @cv = Cv.find(params[:id])
end

def new
  @cv = Cv.new
end

def create
  @cv = Cv.new(cv_params)
  if @cv.save
    # messing with alerts!
    flash[:notice] = "Wine Successfully added"
    redirect_to  cvs_path
  else
    render :new
  end
end

def edit
  @cv = Cv.find(params[:id])
end

def update
  @cv= Cv.find(params[:id])
  if @cv.update(cv_params)
    redirect_to cvs_path
  else
    render :edit
  end
end

def destroy
  @cv = Cv.find(params[:id])
  @cv.destroy
  redirect_to cvs_path
end

private
def cv_params
  params.require(:cv).permit(:name)
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authorize_admin, only: [:edit]
  def index
    @cv = cv.find(params[:cv_id])
    @jobs = Job.all
    @schools = School.all
    @projects = Project.all
  end

  def new
    @cv = Cv.find(params[:cv_id])
    @job = @cv.jobs.new
  end

  def create
    @cv = Cv.find(params[:cv_id])
    @job = @cv.jobs.new(job_params)
    if @job.save
      flash[:alert] = "Job Successfully Added"
      redirect_to cv_path(@job.cv)
    else
      flash[:alert] = "Rating should be between 1 and 5"
      render :new
    end
  end

  def edit
    @cv = Cv.find(params[:cv_id])
    @job = Job.find(params[:id])
  end

  def update
    @cv = Cv.find(params[:cv_id])
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:alert] = "Job Successfully Updated"
      redirect_to cv_path(@job.cv)
    else
      flash[:alert] = "Rating should be between 1 and 5"
      render :edit
    end
  end

  def destroy
    @cv = Cv.find(params[:cv_id])
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to cv_path(@job.cv)
  end

private
  def job_params
    params.require(:job).permit(:name, :date_start, :date_end, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authorize_admin, only: [:edit]
  def index
    @cv = cv.find(params[:cv_id])
    @jobs = Job.all
    @schools = School.all
    @projects = Project.all
  end

  def new
    @cv = Cv.find(params[:cv_id])
    @project = @cv.projects.new
  end

  def create
    @cv = Cv.find(params[:cv_id])
    @project = @cv.projects.new(project_params)
    if @project.save
      flash[:alert] = "Project Successfully Added"
      redirect_to cv_path(@project.cv)
    else
      flash[:alert] = "Rating should be between 1 and 5"
      render :new
    end
  end

  def edit
    @cv = Cv.find(params[:cv_id])
    @project = Project.find(params[:id])
  end

  def update
    @cv = Cv.find(params[:cv_id])
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:alert] = "Project Successfully Updated"
      redirect_to cv_path(@project.cv)
    else
      flash[:alert] = "Rating should be between 1 and 5"
      render :edit
    end
  end

  def destroy
    @cv = Cv.find(params[:cv_id])
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to cv_path(@project.cv)
  end

private
  def project_params
    params.require(:project).permit(:url)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
    before_action :authorize_admin, only: [:edit]
  def index
    @cv = cv.find(params[:cv_id])
    @schools = School.all
    @jobs = Job.all
    @projects = Project.all
  end

  def new
    @cv = Cv.find(params[:cv_id])
    @school = @cv.schools.new
  end

  def create
    @cv = Cv.find(params[:cv_id])
    @school = @cv.schools.new(school_params)
    if @school.save
      flash[:alert] = "School Successfully Added"
      redirect_to cv_path(@school.cv)
    else
      flash[:alert] = "Rating should be between 1 and 5"
      render :new
    end
  end

  def edit
    @cv = Cv.find(params[:cv_id])
    @school = School.find(params[:id])
  end

  def update
    @cv = Cv.find(params[:cv_id])
    @school = School.find(params[:id])
    if @school.update(school_params)
      flash[:alert] = "School Successfully Updated"
      redirect_to cv_path(@school.cv)
    else
      flash[:alert] = "Rating should be between 1 and 5"
      render :edit
    end
  end

  def destroy
    @cv = Cv.find(params[:cv_id])
    @school = School.find(params[:id])
    @school.destroy
    redirect_to cv_path(@school.cv)
  end

private
  def school_params
    params.require(:school).permit(:name, :date_start, :date_end, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/edit.html.erb
<h1>Edit Your Blog</h1>
<div class="field">
<%= form_for [@cv, @blog] do |f| %>
<br>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %><br />
  <%= f.text_field :description %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/blogs/new.html.erb
<h1>Create a New Blog</h1>
<div class="field">
<%= form_for [@cv, @blog] do |f| %>
<br>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %><br />
  <%= f.text_field :description %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/cvs/edit.html.erb
<h1>Edit <%= @cv.name %></h1>
<%= form_for @cv do |f| %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="actions">
  <%= f.submit "Update" %>
</div>

<button class="btn ">
  <%= link_to "Delete This Portfolio", cv_path(@cv),
                    :data => {:confirm => "Are you sure?",
                    :method => "delete"} %>
                  </button>
<% end %>

app/views/cvs/index.html.erb
<h1>Users</h1>
<% @cvs.each do |cv| %>
  <h4><li>
      <%= link_to cv.name, cv_path(cv) %>
  </li></h4>
<% end %>

app/views/cvs/new.html.erb
<h1>Create a Portfolio</h1>
<br>
<div class="field">
<%= form_for @cv do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
<br><br>
<div class="actions">
  <%= f.submit "Submit Portfolio" %>
</div>
<br><br><br><br><br>
<% end %>

app/views/cvs/show.html.erb
<h2><%= @cv.name %></h2>
<h2>Job History</h2>
<ul>
   <% @cv.jobs.each do |job| %>
     <li>
       <h5><%= job.name %></h5>
       <h5><%= job.date_start %></h5>
       <h5><%= job.date_end %></h5>
       <h5><%= job.description %></h5>

       <%= link_to "Edit job", edit_cv_job_path(@cv, job), class: 'red' %> |
       <%= link_to "Delete ", cv_job_path(@cv, job), class: 'red',
                                :data => {:confirm => "Are you sure?",
                                               :method => "delete"} %>
     </li>
     <br>
   <% end %>
 </ul>
 <h2>Education</h2>
 <ul>
    <% @cv.schools.each do |school| %>
      <li>
        <h5><%= school.name %></h5>
        <h5><%= school.date_start %></h5>
        <h5><%= school.date_end %></h5>
        <h5><%= school.major %></h5>

        <%= link_to "Edit school", edit_cv_school_path(@cv, school), class: 'red' %> |
        <%= link_to "Delete ", cv_school_path(@cv, school), class: 'red',
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
      <br>
    <% end %>
  </ul>
  <h2>Project Links</h2>
  <ul>
     <% @cv.projects.each do |project| %>
       <li>
         <h5><%= project.url %></h5>

         <%= link_to "Edit project", edit_cv_project_path(@cv, project), class: 'red' %> |
         <%= link_to "Delete ", cv_project_path(@cv, project), class: 'red',
                                  :data => {:confirm => "Are you sure?",
                                                 :method => "delete"} %>
       </li>
       <br>
     <% end %>
   </ul>
   <h2>Blog</h2>
   <ul>
      <% @cv.blogs.each do |blog| %>
        <li>
          <h5><%= blog.title %></h5>
          <h5><%= blog.description %></h5>

          <%= link_to "Edit blog", edit_cv_blog_path(@cv, blog), class: 'red' %> |
          <%= link_to "Delete ", cv_blog_path(@cv, blog), class: 'red',
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
        </li>
        <br>
      <% end %>
    </ul>

<br>
<p><%= link_to 'Create', new_cv_job_path(@cv) %> new employment history.</p>
<p><%= link_to 'Create', new_cv_school_path(@cv) %> new education history.</p>
<p><%= link_to 'Create', new_cv_project_path(@cv) %> new project.</p>
<p><%= link_to 'Create', new_cv_blog_path(@cv) %> new blog.</p>
<br>
<p><%= link_to 'Edit', edit_cv_path %> name.</p>

<br><br><br><br><br><br>

app/views/home/index.html.erb
<h2>Welcome!</h2>
<h3>To our portfolio site.</h3>
<br><br>
<hr>
<h4>Users, <%= link_to 'sign in', new_user_session_path %> to begin <%= link_to ' creating', new_cv_path %> your portfolio!</h4>
<hr>
<br><br>
<hr>
<h4>Employers, <%= link_to 'click here', cvs_path %> to view potential cvs.</h4>
<hr>
<br><br>
<hr>
<h4>Already have an account? <%= link_to 'click here', cvs_path %> to find your account and edit your account.</h4>
<hr>

app/views/jobs/edit.html.erb
<h1>Edit Your Employment</h1>
<div class="field">
<%= form_for [@cv, @job] do |f| %>
<br>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  <br>
  <%= f.label :date_start %><br />
  <%= f.text_field :date_start %>
  <br>
  <%= f.label :date_end %><br />
  <%= f.text_field :date_end %>
  <br>
  <%= f.label :description %><br />
  <%= f.text_field :description %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/jobs/new.html.erb
<h1>Enter Job History</h1>
<div class="field">
<%= form_for [@cv, @job] do |f| %>
<br>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  <br>
  <%= f.label :date_start %><br />
  <%= f.text_field :date_start %>
  <br>
  <%= f.label :date_end %><br />
  <%= f.text_field :date_end %>
  <br>
  <%= f.label :description %><br />
  <%= f.text_field :description %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Portefeuille", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">

                <% if current_user %>
                    <li> <%= link_to current_user.email, edit_user_registration_path %></li>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                    <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
                <% else %>
                    <li><%= link_to 'Sign Up', new_user_registration_path %></li>

                    <li><%= link_to 'Sign In', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
      </div>
  </nav>
        <footer class="footer">

          <a></a>

      </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/menu" %>
    <div class="container">

      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Edit Project Urls</h1>
<div class="field">
<%= form_for [@cv, @project] do |f| %>
<br>
  <%= f.label :url %><br />
  <%= f.text_field :url %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/projects/new.html.erb
<h1>Enter Project Url</h1>
<div class="field">
<%= form_for [@cv, @project] do |f| %>
<br>
  <%= f.label :url %><br />
  <%= f.text_field :url %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/schools/edit.html.erb
<h1>Edit Education History</h1>
<div class="field">
<%= form_for [@cv, @school] do |f| %>
<br>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  <br>
  <%= f.label :date_start %><br />
  <%= f.text_field :date_start %>
  <br>
  <%= f.label :date_end %><br />
  <%= f.text_field :date_end %>
  <br>
  <%= f.label :major %><br />
  <%= f.text_field :major %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>
</div>

app/views/schools/new.html.erb
<h1>Enter Project History</h1>
<div class="field">
<%= form_for [@cv, @school] do |f| %>
<br>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  <br>
  <%= f.label :date_start %><br />
  <%= f.text_field :date_start %>
  <br>
  <%= f.label :date_end %><br />
  <%= f.text_field :date_end %>
  <br>
  <%= f.label :major %><br />
  <%= f.text_field :major %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>
</div>